### ISSUE TITLE
images which we add on market not display on site

### ISSUE THREAD

**Issue by sachinbanugariya** [RiverVanRain/market#1]
the plugin is violating the coding guidelines for elgg 2.3,
images which we include when creating market is not dispaying.

![market111](https://cloud.githubusercontent.com/assets/22053179/23577538/ccb80cde-00e7-11e7-9afa-71dfce8528c1.png)

**Comment by RiverVanRain** [comment]
Just tested on Elgg 2.3.1 with current version of Market and works very well. No any issue
