### ISSUE TITLE
Mark as sold button takes you to error page

### ISSUE THREAD

**Issue by PerJensen** [RiverVanRain/market#15]
Clicking on the Mark as sold, Open for sell or Send Private Message buttons takes you to an error page:

> The page you are trying to view does not exist or you do not have permissions to view it

**Comment by rohit1290** [comment]
I don't have any error on "Mark as sold" or "Open for sell"
Please ensure that you have removed/deleted all the old files and updated the new files.

**Comment by PerJensen** [comment]
I just tested again on a fresh installation and still get the errors. The ad is marked as sold, so the function works, but forwarding does not work. You end up on the error page, as mentioned. It has this url in my xampp:

> http://localhost/sites/elgg-latest/market/view/91/

**Comment by rohit1290** [comment]
Technically, your url should have been http://localhost/sites/elgg-latest/market/view/91/{title}

The title part is missing from your URL, referring to this:

https://github.com/RiverVanRain/market/blob/57b9dbfe464a829612a68d2f432585b16d86219a/actions/market/open.php#L26

https://github.com/RiverVanRain/market/blob/57b9dbfe464a829612a68d2f432585b16d86219a/actions/market/sold.php#L26

**Comment by PerJensen** [comment]
Any  ideas why  the links does not work? The easy fix was to replace with forward($post->getURL());, but the url's should work.

Do you get errors with Private Message and Group market (group profile page sidebar) buttons, I do?

**Comment by rohit1290** [comment]
Please refer to the latest commit https://github.com/RiverVanRain/market/pull/17/commits/11576749385a419cb560adde2489507e0541c905 and let me know if things are working now.

**Comment by PerJensen** [comment]
Everything is working now with 11576749385a419cb560adde2489507e0541c905
