### ISSUE TITLE
Widgets missing

### ISSUE THREAD

**Issue by PerJensen** [RiverVanRain/market#16]
In Elgg 3.0 I think widgets should be addressed in elgg-plugin.php, like so:

```
'widgets' => [
	'market' => [
		'context' => ['profile', 'dashboard'],
	],
],

```

And remove from start.php:

```

elgg_register_widget_type('market', elgg_echo('market:widget'), elgg_echo('market:widget:description'));

```

**Comment by rohit1290** [comment]
elgg_register_widget_type is a valid function in Elgg 3.0.

**Comment by PerJensen** [comment]
> elgg_register_widget_type is a valid function in Elgg 3.0.

Hmm, I didn't have any widgets untill I added the above fix.

**Comment by rohit1290** [comment]
yes, I have tested it and made the required changes. It should be fixed once RvR merge the pull request.

**Comment by PerJensen** [comment]
Great, thank you.

**Comment by PerJensen** [comment]
To complete the update of widgets, the language file should also be updated. Like this:

> 'widgets:market:name' => 'My Market',
> 'widgets:market:description' => "Showcase your posts on The Market.",

[Elgg learn](http://learn.elgg.org/en/stable/guides/widgets.html?highlight=widgets#magic-widget-name-and-description)

**Comment by rohit1290** [comment]
> To complete the update of widgets, the language file should also be updated

Done
