### ISSUE TITLE
River comment uses wrong language string

### ISSUE THREAD

**Issue by PerJensen** [RiverVanRain/market#18]
When commenting on a Market Post retrieved language string is not from market/languages/en.php but the fall-back from elgg/languages/en.php:

Not used:
```
'river:comment:object:market' => '%s commented on The Market ad %s',

```
Used:
```
'river:object:default:comment' => '%s commented on %s',

```

Also, Market Post update does not work either:

```
'river:update:object:market' => '%s updated the ad %s in The Market',

``

**Comment by rohit1290** [comment]
Have updated the code, this should fix both your comment as well as post update issue.

**Comment by PerJensen** [comment]
Post update notification is working with this fix, but not the comment. Still uses:

> 'river:object:default:comment' => '%s commented on %s',

**Comment by rohit1290** [comment]
Please flush your cache and run an upgrade.

`'river:object:market:comment' => '%s commented on the market ad %s'`

This should fix the problem. I have tested it locally on my system.

**Comment by PerJensen** [comment]
Yes, flushing cache did it. Great, thanks.
