### ISSUE TITLE
"Send Private Message" not working (Elgg 2.3)

### ISSUE THREAD

**Issue by rohit1290** [RiverVanRain/market#2]
You need to change `$owner->guid` to `$entity->owner_guid` at line [76](https://github.com/RiverVanRain/market/blob/6804594491a8e77f9a1b9cddb904364c6770ab5f/views/default/object/market/profile.php#L76) and [79](https://github.com/RiverVanRain/market/blob/6804594491a8e77f9a1b9cddb904364c6770ab5f/views/default/object/market/profile.php#L79) of market/views/default/object/market/profile.php file.

$owner->guid will always return null and the code will not work. Please fix the issue.

**Comment by RiverVanRain** [comment]
https://github.com/RiverVanRain/market/pull/6
