### ISSUE TITLE
Disable "Save" button till the time hypeDropzone upload images

### ISSUE THREAD

**Issue by rohit1290** [RiverVanRain/market#20]
If a user selected 4-5 images to upload and by the time the images are getting upload the user click on save, the image are not getting saved to the ad post.

Solution: By the time hypeDropzone is uploading the images, the "Save" button should be disabled.

**Comment by RiverVanRain** [comment]
I can't recognize it.
Limit is 25 images https://github.com/RiverVanRain/market/blob/master/views/default/forms/market/save.php#L193

And they are saved as the attached images correctly

**Comment by RiverVanRain** [comment]
There is progress bar in the dropzone inputs. When the image download is complete the icon appears also.
Your request should be add in [hypeDropzone](https://github.com/RiverVanRain/hypeDropzone) for **all forms** using its input not market only.

**Comment by rohit1290** [comment]
let me see what can be done.
We can add a js code in dropzone.js that will search for a submit button and disable it on upload start and then enable it on upload complete.

**Comment by RiverVanRain** [comment]
Done https://github.com/RiverVanRain/hypeDropzone/commit/d8ac2b92aba875c21eabe5bb76137b8734db042c
