### ISSUE TITLE
No option to delete ad images on Edit

### ISSUE THREAD

**Issue by rohit1290** [RiverVanRain/market#22]
There is no option to deleted existing image on edit page

**Comment by RiverVanRain** [comment]
The attached images are ElggFile objects. So deleting these files by its owner will be deleted same images from the ad's view.

**Comment by rohit1290** [comment]
Its will be a bad UX if that is the scenario. User add image from market plugin and they need to to go to the file plugin to delete the image. Won't this be confusing for users?

What if the file plugin in not enabled. Like in my site, I don't use file plugin. So how will the user delete the images?

**Comment by RiverVanRain** [comment]
What if the File plugin WILL BE enabled after your changes? Have you tested this scenario?
