### ISSUE TITLE
Use one HypeDropzone for file upload

### ISSUE THREAD

**Issue by rohit1290** [RiverVanRain/market#23]
Instead of using two different hypeDropzone box, can we do something where one single hypeDropzone will be used and the first image will be used as cover image by default. The user will have the option to change the cover image from edit page.

**Comment by RiverVanRain** [comment]
Commit https://github.com/RiverVanRain/market/commit/2cd55132d000a4350cd5ed10fe1a70c0882d1ff9 is better for compatibility with activated / deactivated File plugin. 
Also, I don't want to mix cover icon and the attached images.
