### ISSUE TITLE
Dropzone not working

### ISSUE THREAD

**Issue by PerJensen** [RiverVanRain/market#25]
Nothing happens when dropping files or cliking the field to select files from computer. But the good old cover icon select works.

Elgg 3.0.2, market 3.0, drop 6.0 - localhost.

**Comment by RiverVanRain** [comment]
I can't recognize this issue. All works very well for me: Elgg 3.0.4 Market 3.0 [hypeDropzone](https://github.com/RiverVanRain/hypeDropzone/releases/download/6.0/hypeDropzone-v6.0.zip) 6.0

**Comment by PerJensen** [comment]
All good now, thanks. Don't really know what was wrong, updated everything again and now it's working.
