### ISSUE TITLE
Manifest conflicts with "market_tool" plugin

### ISSUE THREAD

**Issue by rohit1290** [RiverVanRain/market#3]
https://github.com/RiverVanRain/market/blob/6804594491a8e77f9a1b9cddb904364c6770ab5f/manifest.xml#L20,L23

Currently your manifest file is in conflict with market_tool plugin and on the other hand, the market_tool plugin requires marker plugin to work.

Please fix this.

**Comment by RiverVanRain** [comment]
https://github.com/RiverVanRain/market/pull/6
