### ISSUE TITLE
Listing shows wrong icon

### ISSUE THREAD

**Issue by PerJensen** [RiverVanRain/market#32]
Listing shows user icon instead of entity icon, unlike eg files and groups, and tags are shown twice.

![listing](https://user-images.githubusercontent.com/1220345/60386544-71692980-9a96-11e9-90eb-6096592ef71f.jpg)

**Comment by RiverVanRain** [comment]
Fixed by [commit](https://github.com/RiverVanRain/market/commit/8a5df7253bcc7350362bf2f04dc3a9fe0ec940b3)
