### ISSUE TITLE
the images of ads in the plugin "market" are also listed in the files on Elgg

### ISSUE THREAD

**Issue by yurtseverfazli** [RiverVanRain/market#34]
Thanks for this plugin which I find very useful for me. But I realized that the plugin "files " lists the images of ads in the plugin "market", too. This makes a bit mess which the viewers' attention collapse. How can I overcome this? Is it possible to keep the images of  ads away from the files plugin?

**Comment by RiverVanRain** [comment]
[Fixed](https://github.com/RiverVanRain/market/commit/b10d4794831f0eee68593f997b023ca4a832c959)

**Comment by yurtseverfazli** [comment]
Thanks Windows için Posta ile gönderildi Kimden: Nikolai ShcherbinGönderilme: 12 Ocak 2023 Perşembe 19:35Kime: RiverVanRain/marketBilgi: yurtseverfazli; AuthorKonu: Re: [RiverVanRain/market] the images of ads in the plugin "market" are also listed in the files on Elgg (Issue #34) Closed #34 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
