### ISSUE TITLE
No "Market Categories" does not allow me to post the ads

### ISSUE THREAD

**Issue by rohit1290** [RiverVanRain/market#5]
If I keep my "Market Categories" blank, this will not allow me to post any ads. 
Even if while creating Ads there will no field for "Market Categories", yet it will prompts a message the  "Market Categories" is a mandatory field and is missing or blank.

I think this should be open and not limited to few user defined category.

Fix: Remove "marketcategory" from line [48](https://github.com/RiverVanRain/market/blob/master/actions/save.php#L48) of save.php file.

**Comment by RiverVanRain** [comment]
https://github.com/RiverVanRain/market/pull/6
