### ISSUE TITLE
Any plan for upgrading this plugin for v3.x?

### ISSUE THREAD

**Issue by rohit1290** [RiverVanRain/market#8]
Hi RvR, just wanted to know if you have any plans to upgrade this plugin to support Elgg 3.x

**Comment by RiverVanRain** [comment]
Sure. Perhaps, on next week

**Comment by rohit1290** [comment]
https://github.com/RiverVanRain/market/pull/9

**Comment by rohit1290** [comment]
@RiverVanRain 
PR for the plugin to support Elgg 3.0 (https://github.com/RiverVanRain/market/pull/10)
